<!-- 
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 src/lib/models/Ethan.glb --transform
-->

<!-- <script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('src/lib/models/Ethan-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
      <T.Mesh
        geometry={gltf.nodes.EthanBody.geometry}
        material={gltf.nodes.EthanBody.material}
        rotation={[Math.PI, -1.55, Math.PI / 2]}
      />
      <T.Mesh
        geometry={gltf.nodes.EthanGlasses.geometry}
        material={gltf.nodes.EthanGlasses.material}
        rotation={[Math.PI, -1.55, Math.PI / 2]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T> -->

<script lang="ts">
  import { onDestroy } from 'svelte'
  import { GLTF, useGltfAnimations } from '@threlte/extras'
  import { buttonStance, buttonGedanBarai, buttonOiTsuki, buttonAgeUke, buttonTetsui, buttonShutoUke } from '../composables/state'
  
  let currentActionKey = 'stance'
  const { gltf, actions, mixer } = useGltfAnimations()
  $: $actions[currentActionKey]?.play()

  const unsub1 = buttonStance.subscribe(() => {
    console.log('transition to stance')
    transitionTo('stance', 0.3)
  })
  const unsub2 = buttonGedanBarai.subscribe(() => {
    console.log('transition to gedan barai')
    transitionTo('gedan_barai', 0.3)
  })
  const unsub3 = buttonOiTsuki.subscribe(() => {
    console.log('transition to oi tsuki')
    transitionTo('oi_tsuki', 0.3)
  })
  const unsub4 = buttonAgeUke.subscribe(() => {
    console.log('transition to age uke')
    transitionTo('age_uke', 0.3)
  })
  const unsub5 = buttonTetsui.subscribe(() => {
    console.log('transition to tetsui')
    transitionTo('tetsui', 0.3)
  })
  const unsub6 = buttonShutoUke.subscribe(() => {
    console.log('transition to shuto uke')
    transitionTo('shuto_uke', 0.3)
  })
  function transitionTo(nextActionKey: string, duration = 1) {
    const currentAction = $actions[currentActionKey]
    const nextAction = $actions[nextActionKey]
    if (!nextAction || currentAction === nextAction) return
    // if (currentAction === nextAction) return
    // Function inspired by: https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_skinning_blending.html
    nextAction.enabled = true
    if (currentAction) {
      currentAction.crossFadeTo(nextAction, duration, true)
    }
    // Not sure why I need this but the source code does not
    nextAction.play()
    currentActionKey = nextActionKey
  }
  onDestroy(() => {
    unsub1()
    unsub2()
    unsub3()
    unsub4()
    unsub5()
    unsub6()
  })
</script>

<GLTF
  bind:gltf={$gltf}
  url="./src/lib/models/Ethan-transformed.glb"
  useDraco={'./src/lib/models/draco/'}
  position={[0, 0, 0]}
  rotation={[1.5, 0, 0]}
  scale={0.012}
/>